# Generated by Django 2.2 on 2020-04-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_name', models.CharField(max_length=100)),
                ('ans_correct', models.IntegerField(default=0)),
                ('ans_que_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_name', models.CharField(max_length=400)),
                ('que_dis', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuezDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qz_user', models.CharField(max_length=50)),
                ('qz_que_name', models.CharField(max_length=400)),
                ('qz_ans_name', models.CharField(max_length=100)),
            ],
        ),
    ]
